create table TEAM_ACTIVITIES_DETAIL
(
  ID_           NUMBER(10) NOT NULL PRIMARY KEY,
  PROC_INST_ID_ VARCHAR2(64),
  ACCOUNT       VARCHAR2(128),
  COMPANY       NVARCHAR2(128),
  DEPARTMENT    NVARCHAR2(128),
  NAME          NVARCHAR2(128),
  ENTRY_DATE    DATE,
  TRAVEL_DATE   DATE,
  REMARK        VARCHAR2(1024),
  STATUS        NUMBER(10),
  CREATE_BY     VARCHAR2(128),
  CREATE_TIME   DATE,
  UPDATE_BY     VARCHAR2(128),
  UPDATE_TIME   DATE
);
commit;