use gnflow;

drop table ACT_GE_PROPERTY;
drop table ACT_HI_ACTINST;
drop table ACT_HI_ATTACHMENT;
drop table ACT_HI_COMMENT;
drop table ACT_HI_DETAIL;
drop table ACT_HI_IDENTITYLINK;
drop table ACT_HI_PROCINST;
drop table ACT_HI_TASKINST;
drop table ACT_HI_VARINST;
drop table ACT_ID_INFO;
drop table ACT_ID_MEMBERSHIP;
drop table ACT_ID_USER;
drop table ACT_RE_MODEL;
drop table ACT_RU_EVENT_SUBSCR;
drop table ACT_RU_IDENTITYLINK;
drop table ACT_RU_JOB;
drop table ACT_RU_TASK;
drop table ACT_RU_VARIABLE;
drop table ACT_GE_BYTEARRAY;
drop table ACT_ID_GROUP;
drop table ACT_RE_DEPLOYMENT;
drop table ACT_RU_EXECUTION;
drop table ACT_RE_PROCDEF;
