create table PERSONAL_REQUIREMENT_EXCHANGE
(
  ID          NUMBER(10) not null PRIMARY KEY,
  ACCOUNT     VARCHAR2(128),
  NAME        NVARCHAR2(128),
  CREATE_BY   VARCHAR2(128),
  CREATE_TIME DATE,
  UPDATE_BY   VARCHAR2(128),
  UPDATE_TIME DATE,
  STATUS      NUMBER(10),
  REMARK      VARCHAR2(1024)
);
commit;